baseURL: "https://elegant-curran-b41336.netlify.app/"
title: Jeremy Grimault
paginate: 8
theme: hugo-PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true
defaultContentLanguage: fr

# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

languages:
    fr:
        languageName: "French"
        weight: 1
        menu:
            main:
                - name: Search
                  url: search/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 10

    #l2:
        #languageName: "En"
        #weight: 2
        #title: Jeremy Grimault
        #profileMode:
            #enabled: false
            #title: PaperMod
            # imageUrl: "#"
            # imageTitle: my image
            # imageWidth: 120
            # imageHeight: 120
            #subtitle: "☄️ Fast | ☁️ Fluent | 🌙 Smooth | 📱 Responsive"
            #buttons:
             #   - name: Blog
                  #url: posts
            #    - name: Tags
                  #url: tags
        # menu:
        #     main:
        #         - name: Search
        #           url: search/
        #           weight: 10
        #         - name: Tags
        #           url: tags
        #           weight: 10


outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "summary", "content","tags"]
    env: production
    description: "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
    author: Jérémy Grimault
    # author: ["Me", "You"] # multiple authors
    ShowReadingTime: true #affiche le temps de lecture des articles
    defaultTheme: auto
    ShowShareButtons: true  #affiche les liens de partage vers les différents réseaux sociaux
    displayFullLangName: true
    comments: true
    # images: ""
    # assets:
    #   favicon: '<path / external url>'

    # profileMode:
    #     enabled: false
    #     title: PaperMod
    #     imageUrl: "https://media-exp1.licdn.com/dms/image/C4D03AQGcFfkjmTygkw/profile-displayphoto-shrink_200_200/0/1545160937268?e=1613001600&v=beta&t=0SZEP4kgxi-zy4w2VvWNKfYGQvm2skqhdiF0kQrZbSQ"
    #     imageTitle: my image
    #     # imageWidth: 120
    #     # imageHeight: 120
    #     buttons:
    #         - name: Archives
    #           url: archives
    #         - name: Tags
    #           url: tags

    homeInfoParams:
        Title: "Bienvenue \U0001F44B"
        Content: >
            Je m'appelle Jérémy Grimault. Après des expériences en cabinet de conseil je me suis lancé dans le Product Management sur des produits d'Intelligence Artificielle. ![image de présentation](data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBwkJCAsJCQkGBgsICBYJCAgICA8ICQcWIB0iIiAdHx8kKDQsJCYxJx8fLTEtMSkrLjo6Ix8zODMsNygtLisBCgoKDg0ODxAQDy0ZFRkrKysrNy0rKy0rNystKys3LTctNzctKy0tLSstKystKysrKystKysrLSsrKysrKy0rK//AABEIAMgAyAMBIgACEQEDEQH/xAAcAAACAgMBAQAAAAAAAAAAAAAEBQMGAAECBwj/xAA5EAABAwMCBAUBBQgDAQEBAAABAAIRAwQhEjEFQVFhBhMicYGRFCMyobEHJDM0QnLB4RVSYvHwQ//EABoBAAIDAQEAAAAAAAAAAAAAAAMEAQIFAAb/xAAqEQACAgEEAQQCAgIDAAAAAAAAAQIRAwQhMUESIjIzYVFxBRNDgRQjQv/aAAwDAQACEQMRAD8AW0d06stvhJqW/wApxZfXC9bj4YeL3Kn4rP783+0rmyHpG5jqs8V/zzewK3YN9CzsvzSNPRsSeIT+8N5SieCO9eekIXxCf3hvLKn4R+MJN/MHh8sh3+KsDt0TWkPSEo1RUHxsm9uZYOa2NFzI7We1EkLcfC3C2dlomcDf1ImPQoCPUiP6FxyIWjKmjCiaM/KlJwoJIHDPRaAXFeuGnohzdjsPlUZbyQYthBNux/uVPTuGnouVHeSCAFtQmu0LX2lvb5Kkm0EgLr6IX7S3qPqo694GtOxxDQOZ5KJNJM7yR3XutJNNjXVHgSQBAZO0lVPxA2q9svqNMukUxkJzUvG29B9R/qe6XaSf1VRu7qpcVC97nOkwAMADssnU5W9r5BZJKgdlq5/No9ytp/wax1xUqDeCGkLErHDaBLHZZaYTaw/wlTB745ppYfoFsY+wMXuVXxX/ADrT2hc8OdhSeKx+9D6Lnh7fQDvhZ+X5mamjYj8Q/wAy1T8HHrCg8Q/zLVPwf8Y9ki/lYxD5ZDZ5+8Geid2v4B7JK1mqsO0J9QbDB2Gy2NDyydX7UdhbOyHu7yhbML61SnTDRMEiT7BVHi/i2o/VTtG+U0iPMd/EPsms2phi9z3MxySLVXuaNIzUeynzlxhB1/EfD6bIFZtZwMBrATPyqA6vVqGalSq6TMvcStEA7QPZZ8/5Jv2qgTyfRcR4qoz/AAqrs7gjZHUuPWddv43UXHGmpj815/kbZg7golhdAnSZxBVYa/J3uR/ay18QusjSQ6eYMhLjXPV31Sjz61PHqAGwmQQpqdxr3BYRyOET/mKT3VHeVjD7Qepx3UzL8gb/AJpZkjrHMZXBJnnjsiLPfDI8mhs/iR5SuP8AkXJZJ6Fak9/orPMyPN/kaf8AIu6/Urf24uycRkA9Uqk9/oum6p5oOTLJolTZJxK4fUMeozgE9FBZURUqNGDDgD7brV3UgT0BUnATNQvPJ2JWe23NWWXqaLZasDIw0QAAAsWW3q6rE2uBzZBzAmVhv7BLWfVM+H/4T8DNj7ireKx+9Arjhz8R8IrxYz74H2QfDcdoWfm+ZmloxN4h/mG9kRwZhLhzgIbxCf3lvuUVwatDo7JL/MxiDf8AaxzTxU+iPub6laWxq1XtZAIYDu48oCT3d9Ttwaj8QPS0bvPRVXiV/WvKmuo4gARTY3amOwTcdUsMZdtlNZkS27OOIX1S6ruqvJdqOJOAOyFkd8dlxPSR1JM5XYHPrus5zcm23uzKbs6n8+QXbZAxDu4P+FjBO+kdZUwZ6fSWjqJ/RWSKkOqTOByg7FdGro21QBBadwey4IIdj0yZIHXqpTQ1iTLSZkgSFbfrk6yM3R07z1B2PxyXBuXTzcCMdly62cOpzuByXHlmYMqjcivkwqjdvbzJgzBOCO6YW93TqnS8BnUgZSXSQ/pEAwpASHB3eFeOWS7JUi7Wfh2rcs1U3NcCAQQJwiR4PuepPsEf+yi7dWvDbP8AUxzTAcdj2+i9ZFhT/wCrUytS9gM5SUvo8dZ4NrnfV9FxdeEq1Cm6odTtIkiF7Q2xp9GoTiNix1PTDcmDjcb/AOFzztkKcrPnPj9vUtnhj2ubLJBIiVvgR25Scq+/tA4JTq1KBzThxY8tEkDcY9wvPbFp800QS2X6ZG8IC3lY1Bu0WL/knN9NCk+vpwXNaSCsTSyfRt6IYNLIEGBklYtCMdvcHbkw5o/+BMuHpawJnw8Z+U7HsVj7kIfGLYc07yQllhtKc+NW+hp/9BJbA+lIaj5V+jT0nLEvH/47fdT8KHqHsoOPfx2+6I4Vv7BZ7+VjEX/2SA/ENabnRmKbRI5SUnJJzt1HX2RPEajn3FV7jJLyBH0QgBO/0HNByO2zMzz8pyZ0Hdp9ua3Hb85WMaT0EmDKbcOsvMORPeFaEPKgIDStqtUw1rjPbKaW/h66eJgieuFaeF8Op0wPS0EcyMlPaFLEQ0QBkJ/Hpl2yWigHw5cNE6HOjeBKJtODV8NNN2ZhxGyvopDoM4XdO3bvERgDdHjgigbKdU8OvNIQA4mZACX1PC9xGoUwCJgSvRhS7RONlp9Oe/vzUvBGXRB47ecNrUHHzGObnMjBPuhgyOm2AF6pxjh9OvTLS1rTGDC854nZVLeq5hGmDgjYhJ5cHhxwcWD9nN/Ts+K0A9xb5lwGtI2AMgyfZe9tq6hIMgiQQvliyrOoV21JJ0vDomNua+lvCty294VbXLTPm0QTmYOyXWxXI1SYy1nuFFX9eDnoivK91oUc+y6yimrWxVuPcPbUDHva1wp1JIcJkbFeI8QpNtuOVqbYAbVIDRsPZe6+J6zadCo9zy1tMEwDEkd/zXgV3X+0cVdWJDvMqklwwCdlCbtDaeyokub+6qVfKoMqsjBJEuHssTq0tBPmNOku5xK2nFjk+wrg32WIJnw8JYEzsFqx7Fo8oU+NR9y3s4JBYbfAVg8Zn93HuFXbA7bpHU/JE0tI/UxTx4/ft55Ulk/QxxnTDCZPJR8e/mG8sqB9wGU4wSRELNyOsjCTmoykxbUMuJnVJJlcj6ThZEnkInHddhvXlmEJ8ma922TWrROYMx8K18ItzAdGCBAVc4cwOqDEwdhyVzsgAwcoEAJnAgkUMbcEf9R0ATO3/wD3dK6Ts9Ewov27FaUCskMWsHYwJAJUtMCJgYQ7HT3kRgbKZrpHREF2mSQOhXBb8RvK2HfHLK5e4R0nfK4qrArtozt2lUvxPa+Y3zAI0mDHMK4XLgf0MpDxhuqhUjJLTCFkVpknn9SnoJ3MFe0fsXv6lXhdS3e5r229WGAnLAvG3u1apwQTIXoP7Ir9lu65aTomDBOH/HZZrRXL7T22R2UdV2lpPQFL7biDamxB6Ka6rfdOPZDoUjyjzH9qHFjTo/ZmOINRxDgDmIyvK6A+/pd3gZVs/aPc6+IBuoO0gk9lT9eksdvoeCug9zSgqovXDmbbbdFizhlVsAzEgEQtrWgrihyxmmXDzhLUwsCnIiMeRd4xE23sUgsW+n42Vk8Us1WpPQSqtY1MR2hI6peuI9pr8hRx/wDjDtlKm06lV2A4wU64rT866azeTkJjbWFOm3ZsxJPRZmSNzZfLjc5y32Km5pa6DiPyXTBqIHUgKXiLNFy8dHkiRuF1ZNmszfLgShU7FVHeh3wyw8sBzsk5gcgntFwAwQI3J2S/VoZqJDYEk9ksuq11ceinqbTOMGNfum8T8erYxOorgt9CoycPa72IKY0Ht6tGOZgLzf7Ff08tfUdIkFriMLVT/kmxqfXIwYLzCajlr/yJuf0eq290wekuYc4gyi4ByDMiYK8r4fc3bKgLnvwcgkkEd1eOGcQL2DViAJko0Mnl0DafI7A+fZY57MtBBIwY5JXdcRFNrjLcCZPMqkX3G71lZ76b6g1OkNZtCtKaiVtl8uqY7DuEmvqcsc2NwRKrdPxPxIiHU3OjEimZK7p+IqusNuKboeYJLYNNDeSLITENzSNOtVZgFrz+aJ4fdVrRoNJ5ZqMmOfutcUE3tQt9QeAQRsRCHq1W08SMDYrOy7NhaXfB6j4U4+6o1oqOEgQSTurdc8TYLYkuH4eq8E4fxp9tUlsnIkA8lYq/iatUt9LdTZESSheSoF/Vb2Qq8W1hWv6lQGcwMpG5swB1GpT3NfzHEmXEmSSt2jNW+YE5XIYUeEO+C3c0g0kg0zonr0WIThwDKtT1NbJENO5O2FpaWKXpQTdF2lHWTvlL5RVm5aUOQEVuifjjdVm/nDCqRaPG35K68TdNs8f+SFQbZ8VCOjoSesVOBoYfcgpjA68neMom/e+nQLmQCCMkThDW1Vv2oyQJBiUfcNa+kW7yCRHVZMn62NVtIVXFqLui1zw1lXQSHNESEtsaRbdBm+kwSrBckUqdKGgyA0mcgFA0KBZeOfGHNkHlOy5xdoWnBNqv9jA0vM3EjmBzUNwyqxp8tjiAMEDYpja77TyRzaAfyGR+acxwBZmU9w4h5fmM1CDGkyT9AjeF8PvL2lUqF9Sh5TRAqY1HoCFZWWrmu/BPSDMfCKpU6kRobTAMEuyUxHEu3YhkUr2KpSsa/qDmkmnkkiCfkKw8CtvMZJLhAgwf0Ut4dLNO0gziCfZd8ImmwAFokEHlErlGmFim4sC43bVJLaepwaCXmYx3Krd19ooUvOFNpaXFrS5vMZKu5M1SD6pETEh8dZUdazDp1U212EzpgGOuFZwvsWk2mU+14jdOY57aNC4ZSALn02kY+QNkTSr0LymZpNa47iArA21pBhpMp+S05LGsIBULeG06ZJ0tb3Agn3XOFVvZy+yo17YvvAxxFINZBJ5BJeIt01XNy6DAPUK28Stf3qfUGimCY5xsqtetmoT35pDUx34Ga9K+wahS1Hmcp7QtpofGyAsgOfVPbXQW6cZCjHhU0w+KAgbbHzS3eTAR9K1LGudBwY+ilr0fLqawOclFVK9NtucgkmSDuhKPi3Z1eLFdEEVS7aD7nAWLLZ0vJ3lhJ6LEVWc2XZx+UVZH4QcoqyMd/dbuPkXhyT3x+4f7FUBriKz+XrKvl677p/sqBU/jv/vKV/kdlAfxcoguLk064gxJ+qslq01bdr8gjIjmq6yydcXLYkgGVbaTBRohogQAPdZWPH5Sk3wVyZJRct+QS6DXNE6jpEkjYFR1CJDhBBAI9kSG7uwWuBDmnaUJWPbTGAOyvP8AXASO3fIfZkfnITOk7GehEJHavIMfmmlCp7mUbCweRDSkfcxjHJTCSOeeRQlGpjpygFcXV25jHaZMAkkmUzews0cXxmppJkg5A5Imyp+5kggSlltXY8BxeHTBMnKcWBpvOHNGnGTsojuyzfijmq3S+cGTgBE0SfxZIcNpXF4GMMB7XSJ1A7lDMuXM/DFRo3AzCvwLumHvY2MAjuUDcHHvseSKbWa9siBO4BwhLx7YxjGykhpCPiZDWlxglw0qoXrBrPLOyf8AHLoea2lkQ3UY7pFUOp3VI6j1S/QS+CCgCD07phb1COqFY3KKptjKpF+IaAW54cz1RgJLeVTMNJEbtB3Rd1X0g8sJLXqEumSM4IS+WVnZZDThj9RcNoYZ7LFzwRrqpqH0iKZaTsTKxGhvFFYu1wXiURbHCGn5U9Arcx+4HAluXfdu9iqJU/mKn96u9cyx3sqRXxc1P7il/wCS9sR3HygqwumsqaIEkYTX7Q5zS0gjoqoyrou2nIzlWJl5TI/pPVY8MtNromUfO3+AqmX6IGkQf6uagrAmoQ4gwBBGy7Zc03bEDsuXj1auqm3urL2n4nVHcd8IrWWVGtzkboNjoPsUxuWgspPEYeJI6I+Lhg59DCgJbzyt1WNczTETv3WqLDDX6nNAbBHIoG74vQo1NJeMYgCSm1wrFXywC84Q+dVMvEknS0kfouLOpeWxLA2u+TALpMfKPbx6j/1ce7hAKJpcbtjh9MicyCDKqlG7Toh3XBGeHXN20Or1q1IQPRTMH5KbWts23phnqIjJcZJPdADj1uMFrh0MiAuhxu2eYbUbO2lxgom35A7oMLPLktPpJnT0QF3XyWgzG6NLg5mppkEEkhJOI1BRoPqbEtJOduihulZFiLjVWnUuZZp9NMNeepQEtncFLq9ydR3yZlRsuTPPCQlmj5PY4dN0+yjfXDO/cpcbskc1FUquPOULJkvgNGdEtzXLyg3H9VtxXP8AlLtlJSsb+HXgVXZAhhLQTglYhuE4re5WJiE6ihjGvSehThS0jhDyp6TsLfx8gIGVj6HexVMuT+81P7jurjUMh3cGFUL9um5d3ygfyPxx+hzG90Kbk/ffKa2rC9ggap3MpTcH71WDgQBpkGMLzz9wXFzP7J7a0jMkdkXUbDfZdy0cwFlZjhRbUglrn6S7pzH54Tqj6WBupUDtM/VGNrTT0HkQQEAXaHTyJghTMznfG4KtBl2WbhdVj6Wl+kwIiNlDe2lOo/8ADTyMQ0SflK7SqWO5jqJTWlV1RzwYBz9E3F2kLyjTb/IE200CPS4DIBGy6NO0MeZQDnDciIKZNYHDAJxgDmtOof8Ag77jKuo/RRzYNTtaT2wykxgG0gE/Kmt+E0ROqlScTJLiwY9kXSp6eThiAF1WraR0gZjEqaQGUmB3nl21EsbAkQ0TMKoeJbo+WKU/iMkA8gnfEbgS6o90NpgxOypvEa5rudU5Ew0dByQcstqKpCd+65ldPOfZcLKlyyTsKRtKo/8AC1zo3IGAuGH9U/4e6i2idUbSIG6PpsKyyacqSCJCMWzzvIgxEQum28HOPdFXF0PMdpAAJxhCOrSVM4Y4t9lOw6ypBtQbewWKC1qgPkkNjmVir5L8DWOSUS9gqRjsIcH9F2D8dFvY2AiTTP0VV4sP3k8pCswd+YVa4ziv8FB1/wAI3AR1c1PYpjYV3Uxic8ktf/E+UR5wpsxkkQB0Xn0t2TGaj5NsbULt1WuykJJquDQBuSr9RsGfZhQc0OboAII3P/1UXwZa+Ze/aHgu8oQwnOf9L1C3AIHcLW02J+FvsWeZNspPFOF1bU5Dn0yfRUAwPdLmPNM7amnds/ovTatqyowte1rgQQWuEgqpcZ8Ovpk1LUFzZk0juPY/4UzwdxLLPfIut3AjU06hzHMe6ZWz242E8uWVXGuqUn41U3Aw5jhB+Qj6N+z/APoHMI3c0SPoog+nsS3sWq3eNt42hFBoORzPtCrNLiTf6ajHRiJgj4RlPiwG5I7dUdfsA2O3NAbPTYHmlV/WZTa57i1oAJ1E4AXDuJl+G6ncpC0LD7dQuaVRszaPLB0PL5lTWzKJWULjPFTcv8umXCk0786h79kAXemN139hq9HYwcKJzXNwZELMk5W2y9Ab2591wiKgQ7glpIqzYKPs6hLYyIESUvAkx1R76FRluKkOa1zonaUTC3F2SiGtpDyB6s78lF7Ban4WT8qJO2UszPf2WLFi4mz0JhUhCipH8syorviNvQ/HUaSB+Bpkn4C3lKMVu6CRpBU/CrnGv4vTG5WXPiJxxQptby1vyfok1zd1bh01HF3YCISur1MJwcU7YX+5R+yJx9RPfdaBnuuSF0AsmKASm2XLwC5rzVpY1NIqDuNv1j6r0K3bG/uvIfDV3UtuJUX03MaXP8stfhtQHkT3MZ6r2OxqU7mi2rT1NmQ9jhDqRHIj3Wzpst40vwJTbjL9hTBIXFWlqG0qeixTeVPyiOVM5TKpxThFG4nWwNdyqNEOCq17wq4ts6TXpg4ewSQO4XqL7LXyn4UJ4SDyBnkQol/XLnZho56PJvJD/wAOJ6Iq2sXTLi4gDaSvQbrwlRretgFvU31NHpee4Sy54LXtf4lOW7eYzLfn/aElG+S6yqQtsrYbR8qzcHth5NarE/dmm0xgpZZ2lSs8UqTTJMOeRimO/wAK007dtGi23ZgBsF3Mq8p9F/PhI8fsa9Ks99MhrXseW6TzjGFu/wCGNewloiByQ/irg9xwTijgXFzK7zWt6zRAI3z9YTbg99SvaWhxa2q0Q5hIGv2QUlO0+QuOSlt2Uu5oupv0uEQYyEI8K3ce4bu4CIHIKqVWlpIiIwkc2NwbKzjTJeFWhuLllOCQTJ9ldeKcMa7hrmMbHlM1sAGZSHwiwGu5xxAAHZXxjA6mWmCC0gghM6bGvB32clt+zyRwyuUbxe2NveVaW2moYHY5QaSmqk0BNQsWwsUUcM7nitxWxqNFp/oYY+pQJJO8meZMrFiu5yk92SzS1seixYoINgLaxYuJNtcWkObLS0ggjcEZC9o8N133XD6PFKLZdUoxeUhtWLeg64wfhaWJrTydtC+fhFltnMrUhVpZa5sjkR8ckRTH+1ixMPsXRMwfKkaFixCZJ2DjkEm4nxZlN5aALggENo0zLnnusWK+GKk9yrZW6fjIWnExbXtvQsaVZ2gPa6XUyep2jqrc4tI1DS6RIIOCFixXaqTGMb9og8X8Fp8X4eaTgG1aQL7arGWH/a8VJrWtct9VGpQfocAYIOyxYhZdkn2Fi6kx7Q8QitT8q7YDiPMaM/ISbidNmrXTc17SdwsWIWSTlFWM+TklYZ4ZdorHlMK927/T7gLaxMab2InoonjKjpv9cR5jAcfRV+FixJZ/ewLMCxYsQSD/2Q==)
       
            Je suis actuellement Product Manager à [**La Forge**](https://www.la-forge.ai/ " site de La Forge") avec une équipe de doers extraordinaires qui accompagnent les entrepreneurs, investissent et développent leurs produits. 
            
    socialIcons:
        - name: twitter
          url: "https://twitter.com/GrimaultJeremy"
        - name: linkedin
          url: "https://www.linkedin.com/in/j%C3%A9r%C3%A9my-grimault/"

taxonomies:
    category: categories
    tag: tags
    series: series

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
